document.addEventListener('DOMContentLoaded', () => {
  const form = document.getElementById('intake-form')
  const confirmation = document.getElementById('confirmation')
  const previewSection = document.getElementById('letter-preview')
  const letterText = document.getElementById('letter-text')
  const getStartedTop = document.getElementById('get-started')
  const previewBtn = document.getElementById('preview-btn')

  function buildSampleLetter(data) {
    const today = new Date().toLocaleDateString()
    return `Date: ${today}

To: ${data.bureau} Consumer Reporting Agency
Re: Dispute regarding ${data.accountType}

To whom it may concern,

I, ${data.fullName}, am writing to dispute information on my credit file that I believe is inaccurate with respect to the following item: ${data.reason}.

Account details (as provided):
- Account type: ${data.accountType}
- Reported to: ${data.bureau}

Pursuant to the Fair Credit Reporting Act (15 U.S.C. § 1681 et seq.), please investigate this information, verify its accuracy, and correct or remove any information that cannot be verified. Please provide the results of your investigation and any documentation used to verify the information.

This letter is generated by a self-service tool for informational and practical use. It is not legal advice and does not guarantee any specific outcome.

Sincerely,
${data.fullName}
${data.email}
`}

  function showConfirmation(name) {
    confirmation.hidden = false
    confirmation.textContent = `Thanks, ${name}. A sample dispute letter is shown below — review and download as needed.`
  }

  function showPreview(letter) {
    previewSection.hidden = false
    letterText.textContent = letter
    previewSection.scrollIntoView({behavior: 'smooth'})
  }

  if (getStartedTop) {
    getStartedTop.addEventListener('click', () => {
      const el = document.getElementById('fullName')
      if (el) el.focus()
      window.scrollTo({ top: document.getElementById('intake-form').offsetTop - 20, behavior: 'smooth' })
    })
  }

  if (previewBtn) {
    previewBtn.addEventListener('click', (e) => {
      e.preventDefault()
      const formData = new FormData(form)
      const data = Object.fromEntries(formData)
      const letter = buildSampleLetter(data)
      showPreview(letter)
    })
  }

  if (form) {
    form.addEventListener('submit', (e) => {
      e.preventDefault()
      const formData = new FormData(form)
      const data = Object.fromEntries(formData)

      // Display confirmation and a generated sample letter (frontend-only)
      showConfirmation(data.fullName || 'Subscriber')
      const letter = buildSampleLetter(data)
      showPreview(letter)

      // Emulate subscription step: show non-blocking note (no backend)
      console.info('Subscription placeholder: $39/month — implement payments later.')
    })
  }
})